/*******************************************************************************
 * Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com / www.digidna.net
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/*!
 * @file        Vector.mm
 * @copyright   (c) 2015 - Jean-David Gadina - www.xs-labs.com / www.digidna.net
 */

#import <ObjectiveCPP.h>

namespace ObjectiveCPP
{
    NSArray * ArrayFromVector( const std::vector< std::string > & vector )
    {
        return ArrayFromVector< std::string, NSString >( vector, @selector( initWithCPPString: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< bool > & vector )
    {
        return ArrayFromVector< bool, NSNumber >( vector, @selector( initWithBool: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< signed char > & vector )
    {
        return ArrayFromVector< signed char, NSNumber >( vector, @selector( initWithChar: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< unsigned char > & vector )
    {
        return ArrayFromVector< unsigned char, NSNumber >( vector, @selector( initWithUnsignedChar: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< signed short > & vector )
    {
        return ArrayFromVector< signed short, NSNumber >( vector, @selector( initWithShort: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< unsigned short > & vector )
    {
        return ArrayFromVector< unsigned short, NSNumber >( vector, @selector( initWithUnsignedShort: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< signed int > & vector )
    {
        return ArrayFromVector< signed int, NSNumber >( vector, @selector( initWithInt: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< unsigned int > & vector )
    {
        return ArrayFromVector< unsigned int, NSNumber >( vector, @selector( initWithUnsignedInt: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< signed long > & vector )
    {
        return ArrayFromVector< signed long, NSNumber >( vector, @selector( initWithLong: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< unsigned long > & vector )
    {
        return ArrayFromVector< unsigned long, NSNumber >( vector, @selector( initWithUnsignedLong: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< signed long long > & vector )
    {
        return ArrayFromVector< signed long long, NSNumber >( vector, @selector( initWithLong: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< unsigned long long > & vector )
    {
        return ArrayFromVector< unsigned long long, NSNumber >( vector, @selector( initWithUnsignedLongLong: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< float > & vector )
    {
        return ArrayFromVector< float, NSNumber >( vector, @selector( initWithFloat: ) );
    }
    
    NSArray * ArrayFromVector( const std::vector< double > & vector )
    {
        return ArrayFromVector< double, NSNumber >( vector, @selector( initWithDouble: ) );
    }
}
